### ISSUE TITLE
 error: redefinition of 'void colmap::SetQuaternionManifold

### ISSUE THREAD

**Issue by ioir123ju** [colmap/glomap#102]
![image](https://github.com/user-attachments/assets/d9bb8462-9061-494a-8655-ba985b324b76)

**Comment by ahojnnes** [comment]
Looks like you are using the pre-installed colmap version instead. The colmap API changed significantly so this is not easily possible, if you don't pick the right colmap commit. I suggest to just build colmap as part of compiling glomap (ie. set `-DFETCH_COLMAP=ON`).
