### ISSUE TITLE
Prebuilt package for Linux CPU

### ISSUE THREAD

**Issue by hardikdava** [colmap/glomap#105]
Thank you for your great work. I see that there is already a prebuilt package available for windows. Can it be available for Linux CPU version? I know that GPU version for building packages might be very difficult. But it would be good to have linux version for CPU implementation.

Thanks in advance.

**Comment by ahojnnes** [comment]
Building glomap should be relatively straightforward on the popular Linux distributions. I appreciate the request but I don't think we have the cycles to provide pre-built Linux packages. We may address this request throgh a future pyglomap package that will run on most Linux machines.

**Comment by hardikdava** [comment]
@ahojnnes Thanks for reply and yes it is a great idea to have pyglomap package.

**Comment by 1kaiser** [comment]
```
!pip install -q condacolab
import condacolab
condacolab.install()
```

```
!mamba install -y glomap 
```
`!glomap -h`
```
GLOMAP -- Global Structure-from-Motion

Usage:
  glomap mapper --database_path DATABASE --output_path MODEL
  glomap mapper_resume --input_path MODEL_INPUT --output_path MODEL_OUTPUT
Available commands:
  help
  mapper
  mapper_resume
```
