### ISSUE TITLE
Glomap Mapping calculates incorrect Camera Positions

### ISSUE THREAD

**Issue by JohannesKrueger** [colmap/glomap#106]
Hello, I've been testing a lot of datasets with the new Glomap Mapper lately. With a current dataset with comparatively few features (300-2000) per image and a similar scene (almost symmetrical space), the algorithm fails and calculates up to 75% of the camera positions incorrectly. I get a similar result with the Colmap Mapper. The input images are not the problem, they are very sharp and high quality and have a small spatial distance. It seems as if the mapping fails due to the similarity/symmetry of the space. Are there ways to eliminate this error and, if necessary, optimize the mapping parameters?

**Comment by ahojnnes** [comment]
Thanks for the feedback. Symmetry is a known challenge and often failure case for SfM. If you have time to customize the pipeline, I suggest looking into https://doppelgangers-3d.github.io/ and filter the input image pairs that you feed to colmap/glomap. It works very well in practice and can fix many symmetric failure cases.

**Comment by JohannesKrueger** [comment]
Thanks for the quick response, I was looking for exactly that kind of solution. I'll test them straight away
