### ISSUE TITLE
How to filter frames with too few num_points3D

### ISSUE THREAD

**Issue by nmerrillq** [colmap/glomap#110]
Hello,

Thank you for publishing this great work. I have gotten mostly great results from glomap, but on my most recent run I found some of the frames have very high or very small focal lengths after optimization, and all of these frames have about 30 num_points3D in the visualizer or less. I am wondering, is there a way to automatically delete frames that have too few num_points3D? It is easy to do in the visualizer, but I feel like these frames should be automatically deleted during recon.

**Comment by ahojnnes** [comment]
The easiest to achieve this would be to load the reconstruction with pycolmap and write a few lines of Python code to do the filtering.
