### ISSUE TITLE
--BundleAdjustment.optimize_intrinsics seems to have no effect

### ISSUE THREAD

**Issue by nmerrillq** [colmap/glomap#111]
Hello,

I ran the command `glomap mapper --database_path database.db --image_path images/ --output_path sparse_no_intr --BundleAdjustment.optimize_intrinsics 0` but the intrinsics were still optimized to be different than the original ones, and some focal lengths were way too large or too small after optimization which is why I wanted to disable it. I believe this may be a bug.

**Comment by ahojnnes** [comment]
This is expected, as there are other stages than bundle adjustment that optimize the intrinsics. If you also se `--skip_view_graph_calibration 1`, then it should keep the original ones.
