### ISSUE TITLE
On Dense Reconstruction

### ISSUE THREAD

**Issue by santolina** [colmap/glomap#112]
Thank you very much for the excellent work. 

Would it be possible to use the SFM output from glomap for dense reconstruction with colmap (i.e. patch-match stereo and fusion) with additional steps such as manually configuring the below files?
- patch-match.cfg
- fusion.cfg

**Comment by ahojnnes** [comment]
The output of glomap is fully compatible with colmap. Simply run the image undistorter on glomap’s output and then run colmap’s dense reconstruction steps.
