### ISSUE TITLE
Bug Report: Issue with Point3D.bin Output from glomap

### ISSUE THREAD

**Issue by mgaoling** [colmap/glomap#119]
Thank you for your incredible software!

I am using glomap as a pre-processing step for some downstream tasks in colmap, as it is built upon colmap. However, I encountered an issue when attempting to run the following command with the output models from glomap:

`colmap mapper --database_path xxx --image_path xxx  --input_path xxx --output_path xxx `

This command resulted in the following error message:

> F0927 17:39:50.430783 20688 reconstruction.cc:2061] Check failed: point2D.HasPoint3D()
> *** Check failure stack trace: ***
>     @ google::LogMessage::Fail()
>     @ google::LogMessage::SendToLog()
>     @ google::LogMessage::Flush()
>     @ google::LogMessageFatal::~LogMessageFatal()
>     @ colmap::Reconstruction::ResetTriObservations()
>     @ colmap::Reconstruction::DeletePoint3D()
>     @ colmap::Reconstruction::MergePoints3D()
>     @ _ZN6colmap23IncrementalTriangulator5MergeERKNSO_70ptionsEm.localalias
>     @ colmap::IncrementalTriangulator::MergeAllTracks()
>     @ colmap::IncrementalMapper::MergeTracks()
>     @ colmap::CompleteAndMergeTracks()
>     @ colmap::(anonymous namespace) ::IterativeGlobalRefinement)
>     @ colmap::IncrementalMapperController::Reconstruct)
>     @ colmap::IncrementalMapperController::Run()
>     @ colmap::Thread::RunFunc()
>     @ (unknown)
>     @ start_thread
>     @ clone
> [1] 20687 abort (core dumped)

Upon investigating, I discovered that the results produced by glomap contain a small bug: for all 3D points triangulated by exactly two views, while these 3D points are included with pointers (to images) in the point3D.bin, they do not have valid back-pointers from those two images to the respective 3D points.

This inconsistency leads to the error message above. As a temporary workaround, I found that removing those invalid 3D points resolves the issue, allowing colmap to function correctly.

**Comment by lpanaf** [comment]
Hi @mgaoling, thank you very much for reporting the bug. Is it possible for you to open a pull request on this?
