### ISSUE TITLE
intrinsics K in FundamentalFromMotionAndCameras.

### ISSUE THREAD

**Issue by zhan994** [colmap/glomap#124]
I'm working on the two_view_geometry. I found some code [here](https://github.com/colmap/glomap/blob/main/glomap/math/two_view_geometry.cc#L54) in fuction FundamentalFromMotionAndCameras.
```
void FundamentalFromMotionAndCameras(const Camera& camera1,
                                     const Camera& camera2,
                                     const Rigid3d& pose,
                                     Eigen::Matrix3d* F) {
  Eigen::Matrix3d E;
  EssentialFromMotion(pose, &E);
  *F = camera1.GetK().transpose().inverse() * E * camera2.GetK().inverse();
}
```

In this function, parameter `pose` means T_cam2_from_cam1. 
Should the FundmentalMatrix be ` *F = camera2.GetK().transpose().inverse() * E * camera1.GetK().inverse();`, 
rather than ` *F = camera1.GetK().transpose().inverse() * E * camera2.GetK().inverse();`?

**Comment by zhan994** [comment]
I've made a pull request here: https://github.com/colmap/glomap/pull/125#issue-2596523647

**Comment by lionlai1989** [comment]
I think how `FundamentalFromMotionAndCameras` is used matters.
The [caller](https://github.com/colmap/glomap/blob/55e40b11a68b8819e71fdb30773258e20a284451/glomap/processors/view_graph_manipulation.cc#L228) looks like:
```cpp
      FundamentalFromMotionAndCameras(
          camera1, camera2, image_pair.cam2_from_cam1, &image_pair.F);
    }
```

Base on my understanding of essential and fundamental matrix, it looks like a bug indeed.
