### ISSUE TITLE
caculate relative pose

### ISSUE THREAD

**Issue by ChungJin0301** [colmap/glomap#129]
I have one question. The poselib library is used to calculate relative pose in glomap, and I understand that colmap also has a function to calculate relative pose. May I know why you use poselib library instead of colmap?

**Comment by ahojnnes** [comment]
The relative pose estimation routines in poselib provide slightly better relative poses than the one implemented in colmap. This can be (mostly) attributed to a better non linear estimation routine that runs inside LO-RANSAC in poselib. The incremental SFM in colmap actually never uses the relative pose except for the two view initialization. Later stages only use the inlier matches, so no extra special care was taken in colmap to get the best possible relative poses.
