### ISSUE TITLE
Lost many views

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [colmap/glomap#131]
When test on books and boxes, I found that the views of the back are often lost

<img width="376" alt="1730267315670" src="https://github.com/user-attachments/assets/4865cc45-d9fc-4f9f-aae4-90a453694a5d">

any suggestion to improve this?

```
colmap feature_extractor --database_path database_folder/database --image_path outputs/frame_output --ImageReader.single_camera=1
colmap exhaustive_matcher --database_path database_folder/database
glomap mapper --database_path database_folder/database --image_path outputs/frame_output --output_path outputs/migumap_output --Thresholds.min_inlier_num 200
```

And when I set Thresholds.min_inlier_num to 20, the front and back of the book get crossed

<img width="532" alt="1730269709169" src="https://github.com/user-attachments/assets/e1325803-c68c-4c12-a27b-0acb8a209d53">

**Comment by ahojnnes** [comment]
Without providing some sample images, it is hard to make any suggestions.

**Comment by jianghr-shanghaitech** [comment]
Thank you for the reply!
Sample images are like this:
![00014](https://github.com/user-attachments/assets/c151a4dd-4f55-4023-ac3b-f693ae015b7f)
![00018](https://github.com/user-attachments/assets/265a30aa-4a70-461f-937e-30d2505fb058)
![00030](https://github.com/user-attachments/assets/5d5d666a-0a85-4854-9e21-d8f88d45a75c)
![00000](https://github.com/user-attachments/assets/c51fd8bc-dbec-439e-a8c4-00f0852d217b)

**Comment by ahojnnes** [comment]
The front, top and back of the bock contain repetitive structure (e.g., "C++ Primer") that likely causes the reconstruction to collapse. This is a common failure case of standard SfM. You can try approaches like "Doppelganger" to disambiguate image pairs of the front/top/back.

**Comment by jianghr-shanghaitech** [comment]
I will give it a try. Thank you very much for your reply!
