### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by ericzzj1989** [colmap/glomap#134]
Thanks for your great jobs!

I’ve been trying to build the project using ninja but have encountered several errors during the process. To help troubleshoot, could you please provide the specific versions of the dependencies (e.g., ceres, boost, eigen, etc) required for the build? I am particularly interested in the versions for:

Thank you in advance for your help!

**Comment by ahojnnes** [comment]
In case you build colmap with custom dependencies or on a system with outdated packages, I recommend following the vcpkg build instructions. Looking up the vcpkg commit hash in our CI pipeline is the best bet to find the latest working dependencies: https://github.com/colmap/colmap/blob/main/.github/workflows/build-windows.yml#L48
