### ISSUE TITLE
support pose prior?

### ISSUE THREAD

**Issue by bloodhunt3r** [colmap/glomap#19]
I have a dataset with given camera pose (not accurate enough), if I want to modify the code, which part should I look into to adapt the pose prior?

**Comment by lpanaf** [comment]
prior pose is currently not supported by command line interface of GLOMAP, however, you can write your own data loader and refer to [this file](https://github.com/colmap/glomap/blob/main/glomap/exe/global_mapper.cc) to see how you can call global mapper and skip certain steps (such as global positioning) or stuff.
