### ISSUE TITLE
Definition of PosePrior misalignment with colmap database.

### ISSUE THREAD

**Issue by sephyli** [colmap/glomap#34]
I'm working on the data loader for the pose prior.
I found some code [here](https://github.com/colmap/glomap/blob/main/glomap/io/colmap_converter.cc#L191) in fuction ConvertDatabaseToGlomap.

```c++
const colmap::PosePrior prior = database.ReadPosePrior(image_id);
if (prior.IsValid()) {
  ite.first->second.cam_from_world = Rigid3d(
      colmap::Rigid3d(Eigen::Quaterniond::Identity(), prior.position));
} else {
  ite.first->second.cam_from_world = Rigid3d();
}
``` 
Should the pose prior be the camera projection center (T for cam_to_world matirx), rather than T for cam_from_world matrix?

**Comment by ahojnnes** [comment]
Thanks, this is a bug, it should be the projection centers, so there is a `-` missing given no prior orientation. @lpanaf FYI.
