### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by icfixx** [colmap/glomap#49]
Hi,

I am running on Ubuntu 22.04 with the south-building dataset.

after this cmd completed 
`~/dev/glomap/south-building$ glomap mapper --database_path ./database.db --image_path ./images/ --output_path ./sparse`

I see a folder sparse/0/ with cameras.bin  images.bin  points3D.bin
how do i visualize them

**Comment by lpanaf** [comment]
Hi, one simple option is to use `colmap gui`,  then choose import model to visualize things

**Comment by ichsan2895** [comment]
`colmap gui` is the answer. It also compatible with `glomap` output.
![image](https://github.com/user-attachments/assets/5a6b4e96-b6ae-4790-af00-cbff2bd41c1e)

**Comment by ahojnnes** [comment]
This is now also documented in the README.

**Comment by icfixx** [comment]
@ahojnnes  Can you please update the README to show the full shell command to run the COLMAP visualization 

The reconstruction can be visualized using the COLMAP GUI, for example:
```shell
colmap gui --import_path ./output/south-building/sparse/0 --database_path data/south-building/database.db --image_path data/south-building/images/
```

**Comment by WS517** [comment]
Thanks for your great work, I noticed that only sparse point clouds can be generated via glomap, can I further generate dense point clouds via colmap? If so how should I complete this step? Looking forward to your reply, thanks a lot!

**Comment by lpanaf** [comment]
Hi, The output of GLOMAP is what used to be provided by the COLMAP mapper. So you should be able to proceed to dense mapping in a similar as what is done with COLMAP before
