### ISSUE TITLE
Pre-compiled Windows binaries can not use

### ISSUE THREAD

**Issue by Torchmm** [colmap/glomap#61]
Hi,Thank you for your work!
    i download the Pre-compiled Windows binaries and uncompressed it.
than i click the glomap.exe  but have no reaction.

my compute system is window 10。

**Comment by ahojnnes** [comment]
It's a pure command-line utility. Please execute it from your favorite shell, e.g., powershell or cmd.

**Comment by Torchmm** [comment]
thank you ! i finally found how to use it.
