### ISSUE TITLE
How to handle this problem

### ISSUE THREAD

**Issue by luoshuiyue** [colmap/glomap#70]
**Describe the bug**
When I follow the instruction to install COLMAP dependencies running this command `cmake .. -GNinja`. The error occurs.

**To Reproduce**
1. git clone https://github.com/colmap/colmap
2. sudo apt-get install \
    git \
    cmake \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev
3. cd colmap
   mkdir build
   cd build
   cmake .. -GNinja

**Expected behavior**
No errors.

**Screenshots**
![741177df4c67bbd6cca91dbfc133850](https://github.com/user-attachments/assets/439348a4-b205-436b-bf31-862570ba043f)
![3ba3f901760d36dd4688e1b8e9aa232](https://github.com/user-attachments/assets/78206232-b2d1-4ed7-9d32-0de91a8dd254)
![32716e2724c96e5bb31f2e8391b20c9](https://github.com/user-attachments/assets/93c91a94-7835-4a08-a18d-28213af06837)
![6e0fcc792bf8ae52b3d04d2c647adf7](https://github.com/user-attachments/assets/b578dcb7-c66c-4ba0-8b37-e0aac8a764f0)

**Environment:**
 - OS: linux 20.04

**Comment by lpanaf** [comment]
Hi, I have never seen an error before. But can you maybe try to reinstall cmake from the source? 
```
wget https://github.com/Kitware/CMake/releases/download/v3.30.1/cmake-3.30.1.tar.gz
tar xfvz cmake-3.30.1.tar.gz && cd cmake-3.30.1
./bootstrap && make -j$(nproc) && sudo make install
```

**Comment by luoshuiyue** [comment]
I follow your steps , and then run `cmake .. -GNinja` again, some errors remain:
![1724147251993](https://github.com/user-attachments/assets/73bf73b2-c0ca-4a36-9bad-3c4369b88b80)
![1724147277043](https://github.com/user-attachments/assets/8d180baa-1900-474a-9ae4-894c28172434)
![1724147310319](https://github.com/user-attachments/assets/282d1f88-3c1e-453b-a12e-cf123b3f8adf)
![1724147328489](https://github.com/user-attachments/assets/7874d037-17e8-41af-9ced-0050c273f5e8)

**Comment by FeiWang1001** [comment]
I met the same problem. Have tried rebuild CMAKE-3.30.1, cuda-11.7\11;.8, gcc&g++-7\8\10, all met this error:(

**Comment by FeiWang1001** [comment]
> I met the similar problem. Have tried rebuild with CMAKE-3.30.1, cuda-11.7\11;.8, gcc&g++-7\8, all met the error:( Seems like cuda compile problem...
> 
> ![image](https://private-user-images.githubusercontent.com/53425859/360221833-2ccb0849-6454-4894-9a0f-647a2a89e7f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTYzNDMsIm5iZiI6MTcyNDI5NjA0MywicGF0aCI6Ii81MzQyNTg1OS8zNjAyMjE4MzMtMmNjYjA4NDktNjQ1NC00ODk0LTlhMGYtNjQ3YTJhODllN2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAzMDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGY1MTkxYjVjMTc2ZWU0NDM0YmU2YzU3OWU5ZDE0NWY1MGRlMzQ3ZTI2MTdiMjEzMDRjMTc0ZTcyNzUwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Dj3R8UD5tFBwwobgsXqqYeZRdDGkX-Bsbvwu9fTQUI)

I solved this problem by adding "-D CMAKE_CUDA_COMPILER=$(which nvcc) "
Hope it is helpful

**Comment by luoshuiyue** [comment]
@FeiWang1001 Thanks, but I still encounter error:
![1724296689327](https://github.com/user-attachments/assets/fc9330c5-79e6-4b9a-8021-a015688af3d0)

**Comment by lpanaf** [comment]
> > @FeiWang1001 Thanks, but I still encounter error: ![1724296689327](https://private-user-images.githubusercontent.com/25098355/360240697-fc9330c5-79e6-4b9a-8021-a015688af3d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTczNDYsIm5iZiI6MTcyNDMxNzA0NiwicGF0aCI6Ii8yNTA5ODM1NS8zNjAyNDA2OTctZmM5MzMwYzUtNzllNi00YjlhLTgwMjEtYTAxNTY4OGFmM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OTc3NGEzNGU2NzNmNGMyMzFmOGRhMjdiZTg0MzVhNzUwOTVhNmE5OGQ5ZjMxZjZhZmE4OGRiMTdkMTE3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BsCEoVzoKweY_6_bn98ecziHwbKYhmrjLiT9Np891-U)
> 
> It is Eigen problem, not cuda problem anymore:)

This seems to be due to the version mismatch. You would need Eigen3.4 for GLOMAP

**Comment by lpanaf** [comment]
> @FeiWang1001 Thanks, but I still encounter error: ![1724296689327](https://private-user-images.githubusercontent.com/25098355/360240697-fc9330c5-79e6-4b9a-8021-a015688af3d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTc1ODksIm5iZiI6MTcyNDMxNzI4OSwicGF0aCI6Ii8yNTA5ODM1NS8zNjAyNDA2OTctZmM5MzMwYzUtNzllNi00YjlhLTgwMjEtYTAxNTY4OGFmM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNjRlODE3MzYzYjMzOTNmNGVlNzliNmU4YmZhZTU2ZTNlMDFlNDgyOTVlYWM3MWIzMWViZTIwMzcwMzVkNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.906IVfsRk9d_u7jAbueKskEYyaxqbg_1u0ivzSi8DwY)

Yes, as @FeiWang1001 says, this is due to version mismatch of Eigen. GLOMAP requires Eigen to be at least version 3.4 (which you can build from source)
