### ISSUE TITLE
Error Installing Glomap: cmake .. -GNinja || Question: Glomap.exe Release soon?

### ISSUE THREAD

**Issue by JohannesKrueger** [colmap/glomap#71]
Hello at the beginning: Great work, I use Colmap very often and am now happy about the even stronger Glomap.

I have great difficulty installing Glomap on my Win10 PC and always fail with the command:

`cmake .. -GNinja`

Despite installing all dependencies and libraries correctly, it doesn't work.

Is an .exe release similar to Colmap planned? (https://github.com/colmap/colmap/releases) or Are there explicit instructions on how to install Glomap for Win10?

Thank you in advance for all answers!

**Comment by ahojnnes** [comment]
Hi, the glomap 1.0.0 release contains precompiled Windows binaries. These are tested under Win11 but I would expect them to work under Win10 without a problem.

**Comment by gradeeterna** [comment]
Hi, is there an update for the precompiled WIndows binaries coming any time soon?

I have been failing to build with cmake all day, and need the PoseLib OPENCV_FISHEYE support which has been added since the 1.0.0 release - https://github.com/colmap/glomap/pull/54

Thanks!
