### ISSUE TITLE
running Glomap with subprocess In the Jupyter Notebook, during "estimate pose" phase, only one CPU core is running.

### ISSUE THREAD

**Issue by zhj296409022** [colmap/glomap#72]
I can't figure out what the problem is.

**Comment by lpanaf** [comment]
Hi, this should be the expected behavior, we are now not utilizing CUDA

**Comment by zhj296409022** [comment]
i mean, when i run glomap in terminal, it will use almost my cpu core, but it only use one core when i run glomap with subprocess in jupyter notebook environment.

run in jupyter notebook environment
![image](https://github.com/user-attachments/assets/5ecb5668-a322-41a5-a1f5-0825bcb50883)

run in terminal
![image](https://github.com/user-attachments/assets/53241d4f-3d71-4957-879d-6d9217e9dc7e)

**Comment by lpanaf** [comment]
It seems that the openmp is not properly functioning from your screenshot. Can you maybe check to openmp condition for your python environment? I tried to call GLOMAP from python with subprocess as you did, and it seems to use a similar amount of resources as directly calling it from the terminal

**Comment by zhj296409022** [comment]
I've found the problem. I use Ray as the computing framework, it set os.environ['OMP_NUM_THREADS']=1 as default value.
