### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by dscho15** [colmap/glomap#75]
Hello,

Firstly, great work.

Are you planning on realizing a docker image in the near future? :)

BR

**Comment by lpanaf** [comment]
Hi, we have not planned a docker image release recently. However, there is one provided by @prajwalchidananda https://github.com/wayveai/glomap/blob/prajwal/docker/docker/Dockerfile. Can you maybe check whether it works for you?

**Comment by lucascassiano** [comment]
amazing!
