### ISSUE TITLE
GLOMAP Reconstruction Fails with COLMAP's `--image_list_path` Option

### ISSUE THREAD

**Issue by alejandrofontan** [colmap/glomap#81]
When using GLOMAP mapper to reconstruct a map from a database created with COLMAP that utilizes the `--image_list_path` option to filter images, the reconstruction produces completely incorrect results. 

```
colmap feature_extractor \
	--database_path ${database} \
	--image_path ${rgb_path} \
	--image_list_path ${colmap_image_list} \
```

However, when using GLOMAP mapper on a database created with COLMAP without that option, using all images in a folder, it works great.

Could it be that GLOMAP is confusing the images specified in `--image_list_path` with all the images in the `--image_path` directory?

Do you know what might be causing this issue, or do you have any ideas on how I can make it work?

Thanks!

**Comment by lpanaf** [comment]
Hi, thanks for your interest. Can you be more specific on which command you call GLOMAP? GLOMAP should only utilize images recorded in the `database.db` file, and if the database file originally contains all images, then it might be wrong. The `--image_path` is only used for extracting colors in GLOMAP.

**Comment by alejandrofontan** [comment]
Thanks for your comment; you're right. Using `--image_list_path` to filter the images when creating the COLMAP database worked. The issue was somewhere else. I tried providing the calibration in FULL_OPENCV format, which isn't supported by PoseLib #82. That was causing GLOMAP to fail. 
 
I appreciate your help!
