### ISSUE TITLE
glomap support for RGBA images

### ISSUE THREAD

**Issue by visualvlad** [colmap/glomap#87]
Hi. Great method and repo!

Does glomap support RGBA images? Attempting to use RGBA images didn't seem to ignore the parts with alpha=0 and took only the RGB data into account. 

Thanks.

**Comment by lpanaf** [comment]
Hi, thanks for the interest. Yes, you are right, we are not considering the alpha channel of images. If desired, maybe you can consider opening an issue in COLMAP, as the image feature extraction and matching are performed with that tool. For the mapping part, the alpha channel should be less relavant.
