### ISSUE TITLE
Pattern: Consistently worse than COLMAP? What am I doing wrong?

### ISSUE THREAD

**Issue by prajwalchidananda** [colmap/glomap#9]
I ran both COLMAP and GLOMAP for two driving scenes from: https://github.com/wayveai/wayve_scenes.
Surprisingly, I observe that COLMAP is considerably better than GLOMAP on both scenes. 
What is more concerning is that the scenes are pretty easy and GLOMAP performs much worse than expected. This makes me feel there is something I'm missing while running GLOMAP. 

I use [this Dockerfile](https://github.com/wayveai/glomap/blob/prajwal/docker/docker/Dockerfile). I do the following to run the reconstructions:

For GLOMAP:
```
colmap feature_extractor \
    --image_path    ./data/ws_007/images \
    --database_path ./data/ws_007/database.db
colmap exhaustive_matcher \
    --database_path ./data/ws_007/database.db 
glomap mapper \
    --database_path ./data/ws_007/database.db \
    --image_path    ./data/ws_007/images \
    --output_path   ./output_glomap/ws_007/sparse
```

For COLMAP:
```
colmap feature_extractor \
    --image_path    ./data/ws_007/images \
    --database_path ./data/ws_007/database.db
colmap exhaustive_matcher \
    --database_path ./data/ws_007/database.db 
colmap mapper \
    --database_path ./data/ws_007/database.db \
    --image_path    ./data/ws_007/images \
    --output_path   ./output_colmap/ws_007/sparse
```
Scene A (200 frames): 
![scene_007](https://github.com/user-attachments/assets/6f279e3b-c1bf-4308-9ed7-1255c19fc55a)
COLMAP result:
![Screen Recording 2024-07-30 at 7 28 45 PM (1)](https://github.com/user-attachments/assets/4fc97093-a4e1-4060-a525-88ebad4a72ed)
GLOMAP result:
![Screen Recording 2024-07-30 at 7 30 24 PM (1)](https://github.com/user-attachments/assets/ddeae821-db99-4582-a0ef-0a1481188a34)

Scene B (200 frames):
![scene_051](https://github.com/user-attachments/assets/568cf5f3-1724-4fcd-84bb-a1eb36f3ee20)
COLMAP result:
![Screen Recording 2024-07-30 at 7 27 10 PM (1)](https://github.com/user-attachments/assets/6fb89c5d-f393-4a67-b878-22629494d650)
GLOMAP result:
![Screen Recording 2024-07-30 at 7 32 30 PM (1)](https://github.com/user-attachments/assets/0af93ab8-d75e-4ab5-84ae-6a4015ace61e)

Any thoughts on the behavior?
- Am I running GLOMAP incorrectly?
- Is there something specific about the scene that makes it easier for incremental SfM (COLMAP) vs global SfM (GLOMAP)?

**Comment by prajwalchidananda** [comment]
I'm going to try `sequential_matcher` instead of `exhaustive_matcher` to see if that helps

**Comment by waveleaf27** [comment]
same issue , is there any update ? thanks 
@lpanaf

**Comment by prajwalchidananda** [comment]
Okay, tried 3 things:
1. `sequential_matcher`: Helps a little, still splits the pose trajectory
2. `vocab_tree_matcher`: Better than sequential_matcher, still splits the trajectory
3. A key observation from the reconstructions was the high variance in the estimated camera parameters (focal lengths). I added `--ImageReader.single_camera 1` to feature_extractor (tried this with sequential_matcher), and that helps the most. The trajectory now looks like colmap. 

Scene A (200 images):
![Screen Recording 2024-07-30 at 11 42 32 PM](https://github.com/user-attachments/assets/ba1dc686-d9fa-455f-b2ea-c502b5b97f05)

**Comment by prajwalchidananda** [comment]
Tried `--ImageReader.single_camera 1` with `exhaustive_matching`. Works well!
![Screen Recording 2024-07-31 at 12 20 21 AM (1)](https://github.com/user-attachments/assets/ac20d5ef-3aed-4db7-9ad9-addb2898723d)

**Comment by prajwalchidananda** [comment]
@lpanaf Any thoughts on why GLOMAP is sensitive to the `--ImageReader.single_camera 1` parameter and COLMAP is not?

**Comment by lpanaf** [comment]
Thanks for the feedback. @prajwalchidananda you are very correct that having `--ImageReader.single_camera 1` can generally largely boost performance. The reason behind this is that if the images are without given focal lengths (I assume your dataset is like this), the camera intrinsic needs to be estimated with the **View Graph Calibration** component, which works better if there are many connected image pairs (which is not available with video input). However, if each camera needs to be optimized separately, the constraint can be weak. In this case, the reconstruction can be subject to unexpected behavior. However, for COLMAP, as images are added one by one, the focal length is optimized with 2d-3d correspondences, which are more abundant than image pairs, so it may be less sensitive.

**Comment by lpanaf** [comment]
Another thing that might help improve the performance is that if your input images are with high resolution or are blurry, you can try increasing the allowed epipolar error by modifying `--RelPoseEstimation.max_epipolar_error`. For example, make it 4, or 10. @waveleaf27 can you also share your set up of experiments? Can you try the things mentioned by @prajwalchidananda and me to see whether it improves your results?

**Comment by yuancaimaiyi** [comment]
@prajwalchidananda @waveleaf27 
First of all, incremental sfm's inherent robustness and accuracy are better than global sfm. When you choose not to share camera intrinsic , since incremental sfm (colmap) has local ba and global sfm, it will continue to optimize the camera intrinsic( focal and distortion coefficient), however global sfm is only an overall BA. In addition to optimizing the pose, it is difficult to accurately optimize the  intrinsic of each camera.
So the conclusion is:
(1) When you do offline calibration (slamer), you have no choice but to use GLOMAP. I believe GLOMAP can achieve very good results.
(2) When you have not done calibration (surveyor) and it is crowdsourced data, colmap (incremental sfm) is the first choice

**Comment by waveleaf27** [comment]
Thanks for your reply. We have fixed the issue after fixing the camera intrinsic parameters.

**Comment by lpanaf** [comment]
@yuancaimaiyi Thanks for your comments. I also agree with the "inherent robustness and accuracy" comments. Regarding "not done calibration", I think it depends on the intrinsic of the input. For example, if images have a large amount of overlap, as in IMC phototourism, or if camera parameters can be shared as much as possible, as with video input, the **view-graph calibration** engine can perform well, and GLOMAP can also achieve accurate reconstruction.

**Comment by guipotje** [comment]
A trick that you can do if you know the camera intrinsics are shared in the sequence but you don't have access to calibration, is to run COLMAP incremental pipeline on a subset of images with shared intrinsics enabled, and it will robustly estimate the intrinsics. Then, you can use this intrinsics as initial guess for the global pipeline on the entire image set. I suspect this will increase the quality of the global pipeline.

**Comment by vidit98** [comment]
I am trying to train gaussian splats from GLOMAP cameras and I noticed that when using `sequential matcher` the results are worse compared to COLMAP and speed is faster for registration part. However, when I use `exhaustive matcher` the results are comparable to COLMAP but the speed is also comparable, so no gains in using GLOMAP. I am also using `--ImageReader.single_camera 1`. The input is a video file and blurry frames are removed from the video before running COLMAP/GLOMAP

Is GLOMAP more sensitive to matcher being used?
