### ISSUE TITLE
Confused by the Running time and Method Processure

### ISSUE THREAD

**Issue by fearless-pilgrim** [colmap/glomap#97]
Thanks for your generous open-source code contributions to the community. By comparing the code with the paper, I have some confusion about the proposed method. 1) **How is the method running time calculated?** Since I found that this method needs to be fed database(such as feature track, global rotation) as prior, is this prior process time counted? 2) **Confused by the constraints on scale ambiguity.** I found that this method kind of similar to the angle-based translation average BATA, but replacing the camera location direction with the ray from 3D point to camera location, and relaxing the constraints on scale ambiguity $\sum_{ij \in V} \langle \mathbf{t}_j - \mathbf{t}_i, \\mathbf{v}_{ij} \rangle = 1$. Is this the conclusion drawn during the experiment?
Hope everything is fine, expected for your reply.

**Comment by lpanaf** [comment]
Hi, thanks for your interest. For the first question, the run time only includes the mapping part, that is, the feature extraction and matching are not included. However, for the mentioned feature track and global rotation, these two steps are parts of the mapping algorithm and are therefore included. Second question, yes, for the BATA loss, to remove gauge ambiguity, they adopt extra constraints. In our case, we do not constrain the problem and allow the problem to be optimized freely. This is for the simplicity of the cost function.

**Comment by fearless-pilgrim** [comment]
Thanks for your detailed reply, I understand what you mean. Looking forward to your next masterpiece.
